### ISSUE TITLE
虚拟机不能汇编自己反汇编出来的代码吗？

### ISSUE THREAD

**Issue by Asterism12** [BUAA-SE-Compiling/c0-vm-cpp#1]
[out.txt](https://github.com/BUAA-SE-Compiling/c0-vm-cpp/files/3992444/out.txt)
我的编译器汇编出这段代码，用虚拟机生成二进制文件(-a)，然后再反汇编回去(-d)，然后再汇编(-a)会报错：
`line 2 :
    0 I 0x2A # 42
invalid line`

**Comment by fazdzz** [comment]
说一下环境吧，我这边用你的文件测试没有问题

**Comment by Asterism12** [comment]
windows10 家庭版

**Comment by fazdzz** [comment]
那不应当，确认你已经pull了repo的最新commit？

**Comment by Asterism12** [comment]
“存储库已最新。没有要拉取的更改。”
应该是最新的

**Comment by fazdzz** [comment]
`-a out.txt out`
`-d out sout`
`-a sout`
这是我尝试复现的路径，请问您是这样吗

**Comment by Asterism12** [comment]
shunbian
![invaildline](https://user-images.githubusercontent.com/49605626/71322141-27ba4280-24ff-11ea-8267-47c8f62e82cd.png)

[vmout.txt](https://github.com/BUAA-SE-Compiling/c0-vm-cpp/files/3992476/vmout.txt)

附上截图和它生成的二进制代码

**Comment by Asterism12** [comment]
![line2](https://user-images.githubusercontent.com/49605626/71322194-de1e2780-24ff-11ea-87ef-ae580020d446.png)
我的过程也是这样的

**Comment by Asterism12** [comment]
顺便一提这份汇编代码生成的二进制文件无法运行，会提示whileFun函数没有返回（但我所有的函数末尾都加了ret）

**Comment by Asterism12** [comment]
我在vs中用了“生成”->"全部清理"，然后重新生成以后解决了这个问题……
所以我认为是Build里的版本比较旧的缘故……

我好像用vs经常会遇到vs不会根据最新的更改重新生成的问题

**Comment by Asterism12** [comment]
重做一遍发现还是有问题，并不是版本原因

**Comment by Asterism12** [comment]
我今天在docker里运行也有这个错误

**Comment by fazdzz** [comment]
您好，我试了很多编译选项，在docker里也尝试make了很多次，但是从来没有发生过问题。
不如您提供一下您编译vm的编译选项

**Comment by Asterism12** [comment]
我按照标准的编译方式编译后执行仍然是同样的结果
`mkdir build`
`cd build`
`cmake ..`
`make # mingw32-make`

我的舍友用相同的步骤也会遇到一样的问题。

测试了一下发现把.constants字段、.start字段和.functions字段虚拟机生成的注释删去就能编译了，似乎虚拟机只支持.F0，.F1，.F2...后的注释，其他的地方的注释都会报错……

**Comment by fazdzz** [comment]
https://github.com/BUAA-SE-Compiling/c0-vm-cpp/blame/master/src/file.cpp#L313

某次调整了trim的代码，但是忘记修改删注释的代码了

**Comment by Asterism12** [comment]
请问算勘误吗(。・∀・)ノ

**Comment by fazdzz** [comment]
> 请问算勘误吗(。・∀・)ノ

算
